SUPABASE_URL=https://soeodxmlvcthyvgjjfgx.supabase.co/
SUPABASE_KEY=sb_publishable_yZk5GXadrQS84nizR6gIWg_aAdmmUQX


user=postgres.soeodxmlvcthyvgjjfgx
password=nAwkof-qusva0-qavtas
host=aws-1-eu-west-3.pooler.supabase.com
port=6543
dbname=postgres
